; A file containing the morse code alphabet that has been converted into hexadecimal so that they can be used by the registers
; All the hex values are inverted as the letter code is read backwards in r27


M_A = 0x02 			; ._
M_B = 0x01 			; _...
M_C = 0x05 			; _._.
M_D = 0x01 			; _..
M_E = 0x00 			; .
M_F = 0x04 			; .._.
M_G = 0x03 			; __.
M_H = 0x00 			; ....
M_I = 0x00 			; ..
M_J = 0x0E 			; .___
M_K = 0x05 			; _._
M_L = 0x02 			; ._..
M_M = 0x03 			; __
M_N = 0x01 			; _.
M_O = 0x07 			; ___
M_P = 0x06 			; .__.
M_Q = 0x0B 			; __._
M_R = 0x02 			; ._.
M_S = 0x00 			; ...
M_T = 0x01 			; _
M_U = 0x04 			; .._
M_V = 0x08 			; ..._
M_W = 0x06 			; .__
M_X = 0x09 			; _.._
M_Y = 0x0D 			; _.__
M_Z = 0x03 			; __..
